import PageHeader from "@/components/PageHeader";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <PageHeader />
      {children}
    </>
  );
}
