import PageHeader from "@/components/Common/PageHeader";
import authOptions from "@/utils/authOptions";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Master Dashboard",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <>
      <PageHeader session={session} variant="private" />
      <div className="flex flex-col min-h-screen pt-24">{children}</div>
    </>
  );
}
