import PageHeader from "@/components/PageHeader";
import authOptions from "@/utils/authOptions";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <>
      <PageHeader session={session} />
      {children}
    </>
  );
}
