import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PageHeader from "@/components/Common/PageHeader";
import PageFooter from "@/components/Common/PageFooter";
import { getServerSession } from "next-auth";
import authOptions from "@/utils/authOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <>
      <PageHeader session={session} variant="auth" />
      {children}
    </>
  );
}
